spring:
  application:
    name: timeCapsuleTriggerService
  datasource:
    url: ${CONNECTION_STRING:jdbc:postgresql://localhost:5432/time_capsule_trigger}
    username: ${USERNAME_POSTGRES:postgres}
    password: ${PASSWORD_POSTGRES:1234}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:password}
    connection-timeout: ${RABBITMQ_CONNECTION_TIMEOUT:5000}
  task:
    scheduling:
      pool:
        size: 5

server:
  port: ${SERVER_PORT:8081}

app:
  scheduler:
    cron:
      daily: "0 0 0 * * *" # every day at midnight
  notification:
    exchange: timecapsule.exchange
    routing-key: timecapsule.expired
